config/routes.rb
Rails.application.routes.draw do
  resources :course_skills
  resources :skills
  resources :trapples
  resources :courses
  devise_for :admins
  resources :qualification_ts
  resources :qualifications
  devise_for :users
  resources :friends
 # get 'home/index'
  root 'home#index'
  get 'ilos/index'
 	get 'home/about'
get 'process/about'
  get 'iso/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'qualifications/index'
  get 'readmore/index'
  get 'qualification/index'
  get 'register/index'
  get 'login/index'
  get 'about/index'
  get 'home/login'
  get 'view/index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coure_skill.rb
class CoureSkill < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
	belongs_to :user
end

app/models/course_skill.rb
class CourseSkill < ApplicationRecord
end

app/models/friend.rb
class Friend < ApplicationRecord

	belongs_to :user
	
end

app/models/qualification.rb
class Qualification < ApplicationRecord
end

app/models/qualification_t.rb
class QualificationT < ApplicationRecord
	belongs_to :user
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/models/trapple.rb
class Trapple < ApplicationRecord
		belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
     has_many :courses
     has_many :friends
     has_many :qualification_ts
     has_many :trapples
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ilos_controller.rb
class IlosController < ApplicationController
  def index
  end
end

app/controllers/iso_Controller.rb
class IsoController < ApplicationController
  def index
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/view_controller.rb
class viewController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coure_skills_helper.rb
module CoureSkillsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/trapples_helper.rb
module TrapplesHelper
end

app/views/home/_header.html.erb
<%= stylesheet_link_tag "main" %>

<% if current_page?(root_path) %>
<nav class="navbar navbar-expand-lg navbar-dark nav-bg", style="margin-bottom: 0px;">
<% end %>

<% unless current_page?(root_path) %>
<nav class="navbar navbar-expand-lg navbar-dark nav-bg" >
<% end %>

  <%= link_to 'Home', root_path, class:" navbar-brand " %>
  

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">





      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      
     <%  if user_signed_in?%>

      <li class="nav-item">

        <%= link_to 'Qualification', new_qualification_t_path , class:"nav-link"%>
          
           </li>


           <li class="nav-item">

        <%= link_to 'Courses', courses_path , class:"nav-link"%>
          
           </li>





                 <li class="nav-item">
                  <%= link_to "Profile",edit_user_registration_path, class:"nav-link" %>
                   </li>

                  


                      <li class="nav-item">
                    <%= link_to "ILO's Standard",ilos_index_path, class:"nav-link" %>
                     </li>



 <li class="nav-item">
                    <%= link_to "Sign Out",destroy_user_session_path,method: :delete, class:"nav-link" %>
                     </li>


                 <li class="nav-item">
                <%= link_to "have Trouble?",new_trapple_path, class:"nav-link" %>
                 </li> 

                    

                  <% elsif admin_signed_in? %>

      <li class="nav-item">

        <%= link_to 'Qualifications Submited ', qualification_ts_path , class:"nav-link"%>
          

                 <li class="nav-item">
                  <%= link_to "Trouble submited",trapples_path, class:"nav-link" %>
                   </li>

                   <li class="nav-item">
                    <%= link_to "Sign Out",destroy_admin_session_path,method: :delete, class:"nav-link" %>
                     </li>

  
     <% else %>
                       <li class="nav-item">
                        <%= link_to "Sign UP",new_user_registration_path, class:"nav-link" %>
                         </li> 

                         <li class="nav-item">
                          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
                           </li>

                           <li class="nav-item">
                          <%= link_to "Sign in as Admin", admin_session, class:"nav-link" %>
                           </li>
     <% end %>


      </ul>
    
    </div>
  </div>
</nav>




<% if current_page?(root_path) %>

  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://t4.ftcdn.net/jpg/02/75/97/99/240_F_275979983_YMLMDRfpKmrouw0buxo8Dv8fQZ2pKtMj.jpg" class="d-block w-100" alt="iso 1">
      <div class="carousel-caption d-none d-md-block">
        <h5>ILO's</h5>
        <p>your way to improve your education</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://aiic2.in1touch.org/uploaded/web/Photos%20siteweb/2-5-1-AIIC_and_ISO.png" class="d-block w-100" alt="iso2">
      <div class="carousel-caption d-none d-md-block">
        <h5>ISO</h5>
        <p>all you want to know about iso in 1 website</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://t4.ftcdn.net/jpg/02/87/11/95/240_F_287119557_rGs0voYHpaeguyrASYa8Yk6KP4jG97Rr.jpg" class="d-block w-100" alt="iso3">
      <div class="carousel-caption d-none d-md-block">
        <h5>ISO</h5>
        <p>how that improve your collage education</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<% end %>

app/views/home/about.html.erb
<h1>About .....</h1>

app/views/home/index.html.erb
  <body style="background-color:#262626;color:#fff" class="theme-red" id="offcanvas-content">

<h2>Benefits of Education are Societal and Personal</h2>
<p>
Those who get an education have higher incomes, have more opportunities in their lives, and tend to be healthier. Societies benefit as well. Societies with high rates of education completion have lower crime, better overall health, and civic involvement.
</p>
<br>
<ins>Poverty Reduction</ins>
<br>
Lack of access to education is considered the root of poverty. Not getting an education can lead to a cycle of poverty. However,<mark>access to education can mean getting out of that cycle.</mark><br>
<br> <br>

 <h3>1. Healthier Lifestyle<h3>
<h6>
People with better education tend to live longer and have healthier lifestyles. According to research, people with higher education have a one-third lower risk of heart disease. Degree holders are also less likely to smoke and more likely to get regular exercise.
</h6>
</br> </br>
<h3>2. Experimentation and Diversity are a Benefit of Education:</h3>
A personal benefit to getting an education is the opportunity to grow as an individual, experiment with what you are passionate about, and find yourself. You will be exposed to a diverse set of people and ideas which expand the mind.

 <br>
 <ins>Connecting Across Borders</ins><br>
 The new world of digital education is helping those who get an education to connect across the globe with people from other cultures. Students can collaborate together across borders, increasing cultural awareness and worldliness of the individuals.

</br></br>

<h3>4. Pursuing Your Passion</h3>
When you feel passionate about something, you want to immerse yourself in that topic. Education gives you the space to do so. In addition, you may find new passions, or new areas of interest within your field of study.<br>

<ins>Sense of Accomplishment</ins><br></br>


Finishing any degree — whether it is a high school degree or higher education — is an accomplishment. Graduating gives students a huge sense of accomplishment and gives them the confidence needed to go out into the world and make something of themselves.

<h3>5. Personal Development of Skills</h3>
Students are required to go through many types of assignments, discussions, courses, and more during their time in education. Therefore, they end up with a wonderful skill set that translates into the workforce.

 </br></br>

In addition, from extracurriculars, students learn arts, sports, and more that help them personally in life and to connect with others.
<br>
<ins>More Productivity</ins>
<br>
Those with an education have had more on their plate, and succeeded through it. They know how to manage their time and talents and be productive. After graduation, students can carry that productive energy into the workforce.
<br></br></br>

 <ins>Better Communication</ins><br>
 Students are required to turn in written assignments, work in groups, participate in discussions, or present in front of others. This leads to excellent written communication, speaking skills, and group communication.<br>

<ins>Critical Thinking Skills</ins><br>
 
</br></br>
People with an education can think, and think well. They are taught to ask questions, reflect, and analyze — all critical skills for later success.<br>

<ins>Identification of Skills</ins><br>

Some have skills that they haven’t yet discovered, and haven’t had the opportunity to expand upon. Education stretches the mind, exposes students to new topics, and pushes students to do better. As a result, students may find skills they didn’t even know they had.<br>
</br></br>
<ins>Greater Sense of Discipline</ins><br>
Students are given increasing amounts of responsibility with each year of education they complete. It is the student’s job to manage their time and create their own success, leading to self-discipline abilities for those who succeed.<br>

</br></br>
<h3>6. More Employment is a Benefit of Education</h3>
Degree holders have access to more jobs. For graduates of bachelor’s programs or higher, the unemployment rate is cut in half.
</br></br>

<h3>7. Career Entry and Advancement</h3><br>
College degrees prepare students for a career, or for advancement within their current field. Higher education gives the training and skills necessary for success in a specific area. In addition, many positions require a degree for entry. Some may not even look at a resume where the applicant has no degree.


</br></br>



<h3>8. Economic Growth</h3>

When an entire society is educated, productivity increases, average income increases, and unemployment decreases. This leads to the economic growth and stability of a society as a whole. It starts with education.<br>
<ins>Higher Income as a Benefit of Education</ins><br>
Those with education beyond high school tend to have higher salaries than high school degree holders. Those with no degrees make the lowest salaries on average. For full-time workers in 2017, weekly average wages for those with no degree was $515, followed by high school graduates at $717, and $1,189 for bachelor’s degree holders. Those with graduate degrees made an average of $1,451.
</br></br>
<h3>9. Environmental Benefits</h3>
Climate change is a large part of the conversation today, and society needs to work together to find ways to reduce impact on the earth. Educated individuals that enter the workforce will put their knowledge of climate change into company policies, leading to increased sustainability.

</br></br>
<h3>10. Societal Benefits</h3>
A society that is well educated feels a higher sense of unity and trust within the community. Educated societies lift up the weak and bring a feeling of togetherness among all parts.<br>
<ins>Promotes Equality and Empowerment</ins><br>
Education provides everyone with a sense of empowerment; the idea that they have the choice to change their own life and choose their path. Women with an education have better decision making capabilities and are more likely to take charge of their own lives.<br>
<ins>Promotes Good Citizenship and Civic Involvement</ins><br>
Those with an education tend to be more aware of current political issues, and are more likely to vote. Higher degree holders are twice as likely to volunteer, and 3.5 times more likely to donate money than high school graduates.<br>
<ins>Reduces Crime</ins><br>
Education teaches people the difference between right and wrong, and also exposes children and young adults to experiences of others. Understanding right and wrong and having empathy reduce tendency to commit crimes. Education of a society decreases overall arrests- just one year increase of average education levels of a state decrease state-wide arrests by 11%.<br>
<ins>Reduces Gender-Based Violence</ins><br>
In communities with high rates of education for both genders, gender-based violence is lower. Educated persons are more likely to support gender equality, and are more likely to take efforts to stop and prevent gender-based or domestic violence. Communities that value education for both genders are less likely to have instances of terrorist attacks on girls schools.<br>
<ins>Reduces Child Marriage</ins><br>
Girls with secondary or higher education are three times less likely to marry before the age of 18. Putting education first in a society allows for girls to be seen as people who can get an education and make their own decisions, rather than just a future wife and mother.<br>
<ins>Reduces Maternal Death Rates</ins><br>
Maternal death rates drop significantly in societies with high education rates. Women with no education at all are 2.7 times as likely to die during birth as women with 12 years of education. Women with one to six years of education are twice as likely to suffer maternal mortality. This is because educated mothers are more likely to use health services, even in low socioeconomic settings. Lack of education is also a stressor for women during childbirth. The more stressors a woman has during pregnancy, the higher the likelihood for negative outcomes.

</br></br>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"> 
      <%= link_to "Read more .." ,
          readmore_index_path  %>
            
          </li>
   
  </ol>
</nav>













</div>
</div></div></div></div><div class="vc_row-full-width vc_clearfix"></div><div id="our-work" data-vc-full-width="true" data-vc-full-width-init="false" data-vc-stretch-content="true" class="vc_row wpb_row vc_row-fluid vc_custom_1578431458997 vc_row-has-fill vc_row-no-padding"><div class="wpb_column vc_column_container vc_col-sm-4"><br><div class="vc_column-inner"><div class="wpb_wrapper"><h3 style="font-size: 103px;color: #fff ;line-height: 0;text-align: left" class="vc_custom_heading work-subtitle",style="color:#fff">Our</h3><h3 style="font-size: 103px;text-align: left" class="vc_custom_heading work-title",
style="color:#fff">Work</h3></div></div></div><div class="wpb_column vc_column_container vc_col-sm-8"><div class="vc_column-inner"><div class="wpb_wrapper">
<div class="wpb_text_column wpb_content_element  work-text">
<div class="wpb_wrapper">
<p><span style="color: #fff;"">we check your oranization if it give a high education quality or not , then we teach you how to improve your education quality and in the end we give you an ISO certificate</span></p>
</div>
</div></div><div class="vc_clearfix"></div></div></div>


<link data-minify="1" rel='stylesheet' id='js_composer_front-css' href='https://www.logic-designs.com/wp-content/cache/min/1/wp-content/plugins/js_composer/assets/css/js_composer.min-8ff4f73845cc7c902ac5aa1a2b88508c.css' type='text/css' media='all' />
































<link id="staticAssetCSS0" rel="stylesheet" href="https://cdn.iso.org/resources/wood/3.3.1/wood.full.min.css" media="screen,print,handheld" type="text/css"/>





 
<section id="product-details">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        
         

</div></li></ul>

      </div>
    </div>
  </div>
</section>

</div>
      </div>
    </div>
  </div>


  </br></br></br></br></br></br></br></br></br>



</section><div class="clear"></div>
      <div class="nav-breadcrumb print-footer bg-darkgray">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 small">
              <!-- BREADCRUMB -->
              <ol class="breadcrumb">

    
      <li><a href="" title="Home page"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>
    
        <li >
          <%= link_to "home" ,
          root_path  %>
             
            
        </li>
      
        <li>
          
 <%= link_to "login" ,
         user_session_path %>

        </li>
      
        <li>
          
              <%= link_to "Register" ,
          new_user_registration_path  %>
            
        </li>
      
    
      
    
  </ol><div class="clear"></div>

            </div>
           
          </div>

          <div class="collapse border-top" id="collapseSitemap">
            <div class="row">
              <!-- SITEMAP -->
              <nav role="navigation" aria-label="Sitemap" class="sitemap-footer clearfix small" id="nav-sitemap"></nav><div class="clear"></div>
            </div>
          </div>
        </div>
      </div>

      
      <footer role="contentinfo" aria-label="Footer" class="footer-iso footer-dark bg-darkergray">
        <div class="container">
          <div class="footer-links center-block">
            <!-- FOOTER LINKS -->
            <nav role="navigation" aria-label="Inline Navigation"  ><li role="none" class="noChildren"><p>Contact us</p></li></nav><div class="clear"></div>
          </div>
          <div class="footer-social ss-icon clearfix">
            <ul itemscope itemtype="https://schema.org/Organization">
              <link itemprop="url" href="https://www.iso.org/">
              <li><a itemprop="sameAs" target="_blank" rel="noopener" href="https://www.facebook.com/profile.php?id=100006094989603" title="Facebook"></a></li>
              <li><a itemprop="sameAs" target="_blank" rel="noopener" href="https://twitter.com/Osama99Ahmed" title="Twitter"></a></li>
              <li><a itemprop="sameAs" target="_blank" rel="noopener" href="https://www.youtube.com/channel/UCcPCfO7UvAtieIHyUFyQ5Sw" title="YouTube"></a></li>
              <li><a itemprop="sameAs" target="_blank" rel="noopener" href="https://www.linkedin.com/in/ahmed-osama-765847181/" title="Linkedin"></a></li>
              <li><a itemprop="sameAs" target="_blank" rel="noopener" href="https://www.instagram.com/ahmed_osama_xx/" title="Instagram"></a></li>
              
            </ul>
          </div>
          <p class="lead">We wish that our services help you </p>
          <div class="row">
            <div class="col-md-8 col-md-offset-2 pull-left">
              <p class="text-xs"> If you have any questions or suggestions regarding the accessibility of this site, please contact us 
              <p class="text-sm"> </p>
            </div>
          </div>
        </div>
     
      
      </footer>

    </main>

    


  </body>
</html>