config/routes.rb
Rails.application.routes.draw do
  resources :course_skills
  resources :skills
  resources :trapples
  resources :courses
  devise_for :admins
  resources :qualification_ts
  resources :qualifications
  devise_for :users
  resources :friends
 # get 'home/index'
  root 'home#index'
  get 'ilos/index'
 	get 'home/about'
get 'process/about'
  get 'iso/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'qualifications/index'
  get 'readmore/index'
  get 'qualification/index'
  get 'register/index'
  get 'login/index'
  get 'about/index'
  get 'home/login'
  get 'view/index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coure_skill.rb
class CoureSkill < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
	belongs_to :user
end

app/models/course_skill.rb
class CourseSkill < ApplicationRecord
end

app/models/friend.rb
class Friend < ApplicationRecord

	belongs_to :user
	
end

app/models/qualification.rb
class Qualification < ApplicationRecord
end

app/models/qualification_t.rb
class QualificationT < ApplicationRecord
	belongs_to :user
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/models/trapple.rb
class Trapple < ApplicationRecord
		belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
     has_many :courses
     has_many :friends
     has_many :qualification_ts
     has_many :trapples
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ilos_controller.rb
class IlosController < ApplicationController
  def index
  end
end

app/controllers/iso_Controller.rb
class IsoController < ApplicationController
  def index
  end
end

app/controllers/qualification_ts_controller.rb
class QualificationTsController < ApplicationController
  before_action :set_qualification_t, only: %i[ show destroy ]
  before_action :authenticate_user!, except: [:index, :show ,:destroy]
before_action :correct_user, only: [:edit ]
  # GET /qualification_ts or /qualification_ts.json
  def index
    @qualification_ts = QualificationT.all
  end

  # GET /qualification_ts/1 or /qualification_ts/1.json
  def show
  end

  # GET /qualification_ts/new
  def new
    @qualification_t = current_user.qualification_ts.build
  end

  # GET /qualification_ts/1/edit
  def edit
  end

  # POST /qualification_ts or /qualification_ts.json
  def create
    @qualification_t = current_user.qualification_ts.build(qualification_t_params)

    respond_to do |format|
      if @qualification_t.save
        format.html { redirect_to @qualification_t, notice: "Qualification t was successfully created." }
        format.json { render :show, status: :created, location: @qualification_t }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @qualification_t.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qualification_ts/1 or /qualification_ts/1.json
  def update
    respond_to do |format|
      if @qualification_t.update(qualification_t_params)
        format.html { redirect_to @qualification_t, notice: "Qualification t was successfully updated." }
        format.json { render :show, status: :ok, location: @qualification_t }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @qualification_t.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualification_ts/1 or /qualification_ts/1.json
  def destroy
    @qualification_t.destroy
    respond_to do |format|
      format.html { redirect_to qualification_ts_url, notice: "Qualification Requst was successfully destroyed." }
      format.json { head :no_content }
    end
  end

def correct_user 

@qualification_t = current_user.qualification_ts.find_by(id: params[:id])
redirect_to qualification_ts_path notice:"successfully" if @qualification_t.nil?

end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qualification_t
      @qualification_t = QualificationT.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def qualification_t_params
      params.require(:qualification_t).permit(:first_name, :last_name, :email, :phone, :skills, :user_id)
    end
end

app/controllers/view_controller.rb
class viewController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coure_skills_helper.rb
module CoureSkillsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/qualification_ts_helper.rb
module QualificationTsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/trapples_helper.rb
module TrapplesHelper
end

app/views/qualification_ts/_form.html.erb
<%= form_with(model: qualification_t) do |form| %>
  <% if qualification_t.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(qualification_t.errors.count, "error") %> prohibited this qualification_t from being saved:</h2>

      <ul>
        <% qualification_t.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :first_name, class:"form-control" , placeholder:"+20"  %>
  </div>


    <br>


  <div class="field">
    <%= form.label :Knowledge_and_Understanding_Skills %>
    <%= form.text_field :last_name ,class:"form-control" , placeholder:"Signed/not"%>
  </div>

    <br>

  <div class="field">
    <%= form.label :Intellectual_skills %>
    <%= form.text_field :email ,class:"form-control" , placeholder:"Signed/not"%>
  
  </div>

  <br>

  <div class="field">
    <%= form.label :Professional_and_Practical_Skills %>
    <%= form.text_field :phone ,class:"form-control" , placeholder:"Signed/not" %>
  </div>

  <br>


  <div class="field">
    <%= form.label :General_and_Transferable_Skills  %>
    <%= form.text_field :skills ,class:"form-control" , placeholder:"Signed/not" %>
  </div>

<br>

   <div class="field">
    <h3>your id</h3>
  <%= form.label :user_id , id: :qualification_t_user_id  ,
    class: "form-control", value:current_user.id %>

  </div>


  <br>

 <!-- <%= form.submit %> -->

<input type="submit" name="commit" value="Create Qualification t" data-disable-with="Create Qualification t" class="btn btn-secondary">

<% end %>

app/views/qualification_ts/edit.html.erb
<h1>Edit your skills </h1>
<br> <br>
<%= render 'form', qualification_t: @qualification_t %>
<br>

<%= link_to 'Show', @qualification_t ,class:"btn btn-light"%> |
<%= link_to 'Back', root_path , class:"btn btn-light" %>

app/views/qualification_ts/index.html.erb
<p id="notice" class="btn btn-outline-danger"><%= notice %></p>

<h1>Qualification Requests</h1>
<br> <br>
<table class="table table-striped table-bordered" >

  <thead class="table-dark">
    <tr style="color:#fff">
      <th>phone number</th>
      <th>Knowledge and Understanding </th>
      <th>Intellectual </th>
      <th>Professional and Practical</th>
      <th>General and Transferable</th>
<th>user id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qualification_ts.each do |qualification_t| %>
      <tr style="color:#fff">
        <td><%= qualification_t.first_name %></td>
        <td><%= qualification_t.last_name %></td>
        <td><%= qualification_t.email %></td>
        <td><%= qualification_t.phone %></td>
        <td><%= qualification_t.skills %></td>
        <td><%= qualification_t.user_id %></td>
        <td><%= link_to 'Destroy', qualification_t, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home ', root_path , class:"btn btn-secondary" %>
<br><br>

app/views/qualification_ts/new.html.erb
<link id="staticAssetCSS0" rel="stylesheet" href="https://cdn.iso.org/resources/wood/3.3.1/wood.full.min.css" media="screen,print,handheld" type="text/css"/>




  <body style="background-color:#262626;color:#fff" class="theme-red" id="offcanvas-content">

 
<section id="product-details">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        
          <h3>You must Add all your courses which cover ILO's skills before ask for Qualification&nbsp;

    

            </h3>
         








<br><br>
<%= render 'form', qualification_t: @qualification_t  %>

<br>

<%= link_to 'Back', root_path , class:"btn btn-secondary" %>




















</div></li></ul>

      </div>
    </div>
  </div>
</section>

</div>
      </div>
    </div>
  </div>


  </br></br></br></br></br></br>



</section><div class="clear"></div>
      <div class="nav-breadcrumb print-footer bg-darkgray">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 small">
              <!-- BREADCRUMB -->
              <ol class="breadcrumb">

    
      <li><a href="/home.html" title="Home page"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>
    
       
        <li>
          <%= link_to "home" ,
          root_path  %>
             
            
        </li>
      
        <li>
          
 <%= link_to "login" ,
         user_session_path %>

        </li>
      
        <li>
          
              <%= link_to "qualification" ,
          qualifications_index_path  %>
            
        </li>
      
    
    
      
    
  </ol><div class="clear"></div>

            </div>
           
          </div>

          <div class="collapse border-top" id="collapseSitemap">
            <div class="row">
              <!-- SITEMAP -->
              <nav role="navigation" aria-label="Sitemap" class="sitemap-footer clearfix small" id="nav-sitemap"></nav><div class="clear"></div>
            </div>
          </div>
        </div>
      </div>

      
      <footer role="contentinfo" aria-label="Footer" class="footer-iso footer-dark bg-darkergray">
        <div class="container">
          <div class="footer-links center-block">
            <!-- FOOTER LINKS -->
            <nav role="navigation" aria-label="Inline Navigation"  ><li role="none" class="noChildren"><p>Contact us</p></li></nav><div class="clear"></div>
          </div>
          <div class="footer-social ss-icon clearfix">
            <ul itemscope itemtype="https://schema.org/Organization">
              <link itemprop="url" href="https://www.iso.org/">
              <li><a itemprop="sameAs" target="_blank" rel="noopener" href="https://www.facebook.com/profile.php?id=100006094989603" title="Facebook"></a></li>
              <li><a itemprop="sameAs" target="_blank" rel="noopener" href="https://twitter.com/Osama99Ahmed" title="Twitter"></a></li>
              <li><a itemprop="sameAs" target="_blank" rel="noopener" href="https://www.youtube.com/channel/UCcPCfO7UvAtieIHyUFyQ5Sw" title="YouTube"></a></li>
              <li><a itemprop="sameAs" target="_blank" rel="noopener" href="https://www.linkedin.com/in/ahmed-osama-765847181/" title="Linkedin"></a></li>
              <li><a itemprop="sameAs" target="_blank" rel="noopener" href="https://www.instagram.com/ahmed_osama_xx/" title="Instagram"></a></li>
              
            </ul>
          </div>
          <p class="lead">We wish that our services help you </p>
          <div class="row">
            <div class="col-md-8 col-md-offset-2 pull-left">
              <p class="text-xs"> If you have any questions or suggestions regarding the accessibility of this site, please contact us 
              <p class="text-sm"> </p>
            </div>
          </div>
        </div>
     
      
      </footer>

    </main>

    

  </body>
</html>

app/views/qualification_ts/show.html.erb
<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Well done!</h4>
  <p>you have sumbited your department skills , now you can get your qualification </p>
  <hr>
  <p class="mb-0"> check your skills</p>
</div>

<p>
  <br><br>
  <strong>phone number:</strong>
  <%= @qualification_t.first_name %>
</p>
<br>
<p>
  <strong>organization name:</strong>
  <%= @qualification_t.last_name %>
</p>
<br>
<p>
  <strong>email:</strong>
  <%= @qualification_t.email %>
</p>
<br>
<p>
  <strong>address:</strong>
  <%= @qualification_t.phone %>
</p>
<br>
<p>
  <strong>University Coordinator:</strong>
  <%= @qualification_t.skills %>
</p>
<br><br>
<%= link_to 'Edit', edit_qualification_t_path(@qualification_t) ,class:"btn btn-dark" %> |
<%= link_to 'Back', new_qualification_t_path ,class:"btn btn-light" %>

<br><br>

<br>
 <%= link_to 'qualification', qualifications_path ,class:"btn btn-light" %>













<link data-minify="1" rel='stylesheet' id='js_composer_front-css' href='https://www.logic-designs.com/wp-content/cache/min/1/wp-content/plugins/js_composer/assets/css/js_composer.min-8ff4f73845cc7c902ac5aa1a2b88508c.css' type='text/css' media='all' />









<link id="staticAssetCSS0" rel="stylesheet" href="https://cdn.iso.org/resources/wood/3.3.1/wood.full.min.css" media="screen,print,handheld" type="text/css"/>




  <body class="theme-red" id="offcanvas-content">

 
<section id="product-details">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        
         

</div></li></ul>

      </div>
    </div>
  </div>
</section>

</div>
      </div>
    </div>
  </div>


  </br></br></br></br></br></br></br></br></br>



</section><div class="clear"></div>
      <div class="nav-breadcrumb print-footer bg-darkgray">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 small">
              <!-- BREADCRUMB -->
              <ol class="breadcrumb">

    
      <li><a href="/home.html" title="Home page"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>
    
        <li>
          <%= link_to "home" ,
          root_path  %>
             
            
        </li>
      
        <li>
          
 <%= link_to "login" ,
         user_session_path %>

        </li>
      
        <li>
          
              <%= link_to "qualification" ,
          new_qualification_t_path  %>
            
        </li>
      
    
      
    
  </ol><div class="clear"></div>

            </div>
           
          </div>

          <div class="collapse border-top" id="collapseSitemap">
            <div class="row">
              <!-- SITEMAP -->
              <nav role="navigation" aria-label="Sitemap" class="sitemap-footer clearfix small" id="nav-sitemap"></nav><div class="clear"></div>
            </div>
          </div>
        </div>
      </div>

      
      <footer role="contentinfo" aria-label="Footer" class="footer-iso footer-dark bg-darkergray">
        <div class="container">
          <div class="footer-links center-block">
            <!-- FOOTER LINKS -->
            <nav role="navigation" aria-label="Inline Navigation"  ><li role="none" class="noChildren"><p>Contact us</p></li></nav><div class="clear"></div>
          </div>
          <div class="footer-social ss-icon clearfix">
            <ul itemscope itemtype="https://schema.org/Organization">
              <link itemprop="url" href="https://www.iso.org/">
              <li><a itemprop="sameAs" target="_blank" rel="noopener" href="https://www.facebook.com/profile.php?id=100006094989603" title="Facebook"></a></li>
              <li><a itemprop="sameAs" target="_blank" rel="noopener" href="https://twitter.com/Osama99Ahmed" title="Twitter"></a></li>
              <li><a itemprop="sameAs" target="_blank" rel="noopener" href="https://www.youtube.com/channel/UCcPCfO7UvAtieIHyUFyQ5Sw" title="YouTube"></a></li>
              <li><a itemprop="sameAs" target="_blank" rel="noopener" href="https://www.linkedin.com/in/ahmed-osama-765847181/" title="Linkedin"></a></li>
              <li><a itemprop="sameAs" target="_blank" rel="noopener" href="https://www.instagram.com/ahmed_osama_xx/" title="Instagram"></a></li>
              
            </ul>
          </div>
          <p class="lead">We wish that our services help you </p>
          <div class="row">
            <div class="col-md-8 col-md-offset-2 pull-left">
              <p class="text-xs"> If you have any questions or suggestions regarding the accessibility of this site, please contact us 
              <p class="text-sm"> </p>
            </div>
          </div>
        </div>
     
      
      </footer>

    </main>

    


  </body>
</html>