config/routes.rb
Rails.application.routes.draw do
  resources :course_skills
  resources :skills
  resources :trapples
  resources :courses
  devise_for :admins
  resources :qualification_ts
  resources :qualifications
  devise_for :users
  resources :friends
 # get 'home/index'
  root 'home#index'
  get 'ilos/index'
 	get 'home/about'
get 'process/about'
  get 'iso/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'qualifications/index'
  get 'readmore/index'
  get 'qualification/index'
  get 'register/index'
  get 'login/index'
  get 'about/index'
  get 'home/login'
  get 'view/index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coure_skill.rb
class CoureSkill < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
	belongs_to :user
end

app/models/course_skill.rb
class CourseSkill < ApplicationRecord
end

app/models/friend.rb
class Friend < ApplicationRecord

	belongs_to :user
	
end

app/models/qualification.rb
class Qualification < ApplicationRecord
end

app/models/qualification_t.rb
class QualificationT < ApplicationRecord
	belongs_to :user
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/models/trapple.rb
class Trapple < ApplicationRecord
		belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
     has_many :courses
     has_many :friends
     has_many :qualification_ts
     has_many :trapples
end

app/controllers/course_skills_controller.rb
class CourseSkillsController < ApplicationController
  before_action :set_course_skill, only: %i[ show edit update destroy ]

  # GET /course_skills or /course_skills.json
  def index
    @course_skills = CourseSkill.all
  end

  # GET /course_skills/1 or /course_skills/1.json
  def show
  end

  # GET /course_skills/new
  def new
    @course_skill = CourseSkill.new
  end

  # GET /course_skills/1/edit
  def edit
  end

  # POST /course_skills or /course_skills.json
  def create
    @course_skill = CourseSkill.new(course_skill_params)

    respond_to do |format|
      if @course_skill.save
        format.html { redirect_to @course_skill, notice: "Course skill was successfully created." }
        format.json { render :show, status: :created, location: @course_skill }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /course_skills/1 or /course_skills/1.json
  def update
    respond_to do |format|
      if @course_skill.update(course_skill_params)
        format.html { redirect_to @course_skill, notice: "Course skill was successfully updated." }
        format.json { render :show, status: :ok, location: @course_skill }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_skills/1 or /course_skills/1.json
  def destroy
    @course_skill.destroy
    respond_to do |format|
      format.html { redirect_to course_skills_url, notice: "Course skill was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course_skill
      @course_skill = CourseSkill.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_skill_params
      params.require(:course_skill).permit(:course_code, :skills, :User_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ilos_controller.rb
class IlosController < ApplicationController
  def index
  end
end

app/controllers/iso_Controller.rb
class IsoController < ApplicationController
  def index
  end
end

app/controllers/view_controller.rb
class viewController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coure_skills_helper.rb
module CoureSkillsHelper
end

app/helpers/course_skills_helper.rb
module CourseSkillsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/trapples_helper.rb
module TrapplesHelper
end

app/views/course_skills/_form.html.erb
<%= form_with(model: course_skill) do |form| %>
  <% if course_skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course_skill.errors.count, "error") %> prohibited this course_skill from being saved:</h2>

      <ul>
        <% course_skill.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :course_code %>
    <%= form.text_field :course_code %>
  </div>

  <div class="field">
    <%= form.label :skills %>
    <%= form.text_field :skills %>
  </div>

  <div class="field">
    <%= form.label :User_id %>
    <%= form.text_field :User_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/course_skills/edit.html.erb
<h1>Editing Course Skill</h1>

<%= render 'form', course_skill: @course_skill %>

<%= link_to 'Show', @course_skill %> |
<%= link_to 'Back', course_skills_path %>

app/views/course_skills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Course Skills</h1>

<table>
  <thead>
    <tr>
      <th>Course code</th>
      <th>Skills</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @course_skills.each do |course_skill| %>
      <tr>
        <td><%= course_skill.course_code %></td>
        <td><%= course_skill.skills %></td>
        <td><%= course_skill.User_id %></td>
        <td><%= link_to 'Show', course_skill %></td>
        <td><%= link_to 'Edit', edit_course_skill_path(course_skill) %></td>
        <td><%= link_to 'Destroy', course_skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course Skill', new_course_skill_path %>

app/views/course_skills/new.html.erb
<h1>New Course Skill</h1>

<%= render 'form', course_skill: @course_skill %>

<%= link_to 'Back', course_skills_path %>

app/views/course_skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course code:</strong>
  <%= @course_skill.course_code %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @course_skill.skills %>
</p>

<p>
  <strong>User:</strong>
  <%= @course_skill.User_id %>
</p>

<%= link_to 'Edit', edit_course_skill_path(@course_skill) %> |
<%= link_to 'Back', course_skills_path %>